# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should
# successfully execute a dry-run of the workflow.
include: "rules/common.smk"
include: "rules/assembly.smk"
include: "rules/plasmids.smk"

report: "report/workflow.rst"

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
singularity: "docker://continuumio/miniconda3:4.8.2"

rule all:
    input:
        scapp = expand(opj("results", "scapp", "{assembly}", "{assembly}.confident_cycs.fasta"),
               assembly = assemblies.keys()),
        recycler = expand(opj("results", "recycler", "{assembly}", "{assembly}.cycs.fasta"),
               assembly = assemblies.keys()),
        mpspades = expand(opj("results", "mpspades", "{assembly}", "{f}.gz"),
               f = ["contigs.fasta", "scaffolds.fasta", "assembly_graph.fastg"],
               assembly = assemblies.keys())