# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should
# successfully execute a dry-run of the workflow.
include: "rules/common.smk"
include: "rules/testdata.smk"
include: "rules/assembly.smk"

report: "report/workflow.rst"

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
singularity: "docker://continuumio/miniconda3:4.8.2"

rule all:
    input:
        expand(opj("results", "assembly", "{assembly}", "scaffolds.fasta"),
               assembly = assemblies.keys())