# conda environment file
name: deepbio_gf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.8
  - snakemake-minimal=5.23.0
  - pandas=1.1.1
  - pulp=1.6.8
  - biopython=1.77