__default__:
  # exchange <staff> with your SLURM account id below
  account: staff

  # directories for slurm logs (no need to change these)
  output: "slurm/logs/{rule}.{wildcards}.out"
  error: "slurm/err/{rule}.{wildcards}.err"

# use this cluster config with '--cluster-config config/cluster-largemem.yaml' 
# to run metaspades on a larger memory node
metaspades:
  constraint: mem256GB
  partition: node
